version: '3.8'

services:
  daily-question-service:
    container_name: daily-question-service
    build:
      context: ../  # 프로젝트 루트 디렉토리를 빌드 컨텍스트로 사용
      dockerfile: daily-question-service/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=${DATABASE_URL} # .env 파일에서 로드
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - USER_SERVICE_URL=http://user-service:8000
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
    depends_on:
      - user-service # DB 의존성 제거, user-service에만 의존
    networks:
      - app-network

  user-service:
    container_name: user-service
    build:
      context: ../  # 프로젝트 루트 디렉토리를 빌드 컨텍스트로 사용
      dockerfile: user-service/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=${DATABASE_URL} # .env 파일에서 로드
    networks:
      - app-network

  voice-analysis-service:
    container_name: voice-analysis-service
    build:
      context: ../
      dockerfile: voice-analysis-service/Dockerfile
    ports:
      - "8003:8003"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - S3_BUCKET_NAME=${S3_BUCKET_NAME}
      - TF_SERVING_URL=${TF_SERVING_URL}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
